### ISSUE TITLE
Cannot access offset of type string on string

### ISSUE THREAD

**Issue by peterjaap** [magmodules/magento2-reloadify#13]
We're getting _a ton_ of issues on this route; `/rest/V1/reloadify/language/5/profiles`

Example URL:

```
/rest/V1/reloadify/language/5/profiles?searchCriteria%5BcurrentPage%5D=1&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=from&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=2022-11-23%2019%3A26%3A02&searchCriteria%5BpageSize%5D=100
```

![image](https://user-images.githubusercontent.com/431360/203635678-4ac7f6d5-597a-4741-b534-501fa2e839f5.png)

We're using the latest version;

![image](https://user-images.githubusercontent.com/431360/203635755-043a9750-a9c8-425d-8bd2-92eb01cfd7f9.png)

One of the stack traces;

```
TypeError: Cannot access offset of type string on string in /data/web/releases/20221116104505/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php:373
Stack trace:
#0 /data/web/releases/20221116104505/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(405): Magento\Eav\Model\Entity\Collection\AbstractCollection->addAttributeToFilter()
#1 /data/web/releases/20221116104505/vendor/magento/framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php(89): Magento\Eav\Model\Entity\Collection\AbstractCollection->addFieldToFilter()
#2 /data/web/releases/20221116104505/vendor/magento/framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php(48): Magento\Framework\Api\SearchCriteria\CollectionProcessor\FilterProcessor->addFilterGroupToCollection()
#3 /data/web/releases/20221116104505/vendor/magento/framework/Api/SearchCriteria/CollectionProcessor.php(38): Magento\Framework\Api\SearchCriteria\CollectionProcessor\FilterProcessor->process()
#4 /data/web/releases/20221116104505/vendor/magmodules/magento2-reloadify/Service/WebApi/Profiles.php(138): Magento\Framework\Api\SearchCriteria\CollectionProcessor->process()
#5 /data/web/releases/20221116104505/vendor/magmodules/magento2-reloadify/Service/WebApi/Profiles.php(78): Magmodules\Reloadify\Service\WebApi\Profiles->getCollection()
#6 /data/web/releases/20221116104505/vendor/magmodules/magento2-reloadify/Model/WebApi/Repository.php(142): Magmodules\Reloadify\Service\WebApi\Profiles->execute()
#7 [internal function]: Magmodules\Reloadify\Model\WebApi\Repository->getProfiles()
#8 /data/web/releases/20221116104505/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
#9 /data/web/releases/20221116104505/vendor/magento/module-webapi/Controller/Rest.php(195): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
#10 /data/web/releases/20221116104505/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#11 /data/web/releases/20221116104505/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#12 /data/web/releases/20221116104505/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#13 /data/web/releases/20221116104505/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#14 /data/web/releases/20221116104505/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#15 /data/web/releases/20221116104505/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#16 /data/web/releases/20221116104505/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#17 /data/web/releases/20221116104505/vendor/justbetter/magento2-sentry/Plugin/GlobalExceptionCatcher.php(78): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#18 /data/web/releases/20221116104505/vendor/magento/framework/Interception/Interceptor.php(135): JustBetter\Sentry\Plugin\GlobalExceptionCatcher->aroundLaunch()
#19 /data/web/releases/20221116104505/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#20 /data/web/releases/20221116104505/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#21 /data/web/releases/20221116104505/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#22 /data/web/releases/20221116104505/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#23 {main}
```

**Comment by Frank-Magmodules** [comment]
Hi @peterjaap ,

We are happy to share that we've just released the new [1.5.4](https://github.com/magmodules/magento2-reloadify/releases/tag/1.5.4) version where we have fixed this issue.  
Thank you for opening this issue and for the detailed issue report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by jesse-deboer** [comment]
We are still facing this issue, even on 1.5.4 unfortunately ..

**Update: It happens with getCategories() and getVariants()**

**Comment by Frank-Magmodules** [comment]
Hi @jesse-deboer , we are working on this together with Reloadify, thank you for your patience.

**Comment by peterjaap** [comment]
@Frank-Magmodules thanks, 1.5.5 indeed fixed it;

![image](https://user-images.githubusercontent.com/431360/214293308-98e0c477-ba23-4007-b7d9-09515f1adda4.png)
