### ISSUE TITLE
Incorrect annotations for Magmodules\Reloadify\Api\WebApi\RepositoryInterface

### ISSUE THREAD

**Issue by bartoszkubicki** [magmodules/magento2-reloadify#16]
Annotations for methods from Magmodules\Reloadify\Api\WebApi\RepositoryInterface are incorrect according to https://developer.adobe.com/commerce/php/development/components/web-api/services/. 

1. All methods with annotation `@return array` are incorrect. "Any parameters or return values of type array can be denoted by following any of the previous types by an empty set of square brackets []". 
2. `public function getCarts` lacks second param annotation.

3. Additionally all methods with `SearchCriteriaInterface` parameters are incorrectly specified. Object type is not nullable, but in the same time null is specified as default value. 

Incorrect annotation interrupts requests to `/rest/all/schema` and possibly request to this module itself (haven'y tested that).

**Comment by bartoszkubicki** [comment]
It is possible that this causes integration failure as well - https://github.com/magmodules/magento2-reloadify/issues/10

**Comment by Marvin-Magmodules** [comment]
Hi @bartoszkubicki,

We are happy to share that we’ve just released the new [1.5.5](https://github.com/magmodules/magento2-reloadify/releases/tag/1.5.5) version where we have fixed this issue. Thank you for opening this issue and for the detailed feedback. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by bartoszkubicki** [comment]
@Marvin-Magmodules Thanks for quick fix. Unfortunately 3. is not fixed, but as I said this is out of scope for this issue, just flagging that.
I meant that params are incorrect in function declaration not in annotations. There is SearchCriteriaInterface object required but default value is null. If someone who would call these functions don't pass SearchCriteria code breaks. So correct type would be either ?SearchCriteriaInterface = null or just SearchCriteriaInterface
