### ISSUE TITLE
Pagination introduces error

### ISSUE THREAD

**Issue by peterjaap** [magmodules/magento2-reloadify#6]
Since Pagination has been introduced in 1.4.0, I'm getting one error a whole lot;

`ErrorException: Warning: Illegal string offset 'attribute' in vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php  at line 373`

See for a stack trace; https://sentry.io/share/issue/4e05f46b127a43d589f0411a2b763e5c/

**Comment by peterjaap** [comment]
I have for now suppressed the error by adding an if statement;

```
                if (isset($condition['attribute'])) {
                        $sqlArr[] = $this->_getAttributeConditionSql($condition['attribute'], $condition, $joinType);
                }
```

But I'm guessing there's a filter that isn't set correctly coming from `$filter = $this->json->unserialize(urldecode((string)$this->request->getParam('filter')));`

**Comment by Frank-Magmodules** [comment]
HI @peterjaap ,  
  
We are happy to share that we've just released the new [1.5.0](https://github.com/magmodules/magento2-reloadify/releases/tag/1.5.0) version where we have fixed this issue.   
Thank you again for opening this issue and for the detailed issue report.  

We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by peterjaap** [comment]
@Frank-Magmodules unfortunately this hasn't fixed the issue. We've been running 1.5.0 since Apr 29th and the problem still occurs. Here's the latest event; https://sentry.io/share/issue/ed6940653764495c9cda7ef37c16a4ce/

Weird, looks like that shareable link isn't correct. Here's a screenshot;

![image](https://user-images.githubusercontent.com/431360/168585061-d4e749da-3d84-4d0d-8d35-bef39d57ebc6.png)
